/// Flutter icons NavBar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBar
///      fonts:
///       - asset: fonts/NavBar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavBar {
  NavBar._();

  static const _kFontFam = 'NavBar';
  static const _kFontPkg = null;

  static const IconData_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData_4 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData_add_friends = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
